stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/load_data.py
    - src/get_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv   #will be tracked by DVC

  split_data:
    cmd: python src/split_data.py
    deps:
    - src/split_data.py
    - src/load_data.py
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py
    deps:
    - src/train_and_evaluate.py
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - report/scores.json
        # cache: false
    - report/variables.json
        # cache: false
    outs:
    - saved_models/model.joblib
    
